### ISSUE TITLE
Better handling of one dataloader failing

### ISSUE THREAD

**Issue by motey** [covidgraph/motherlode#4]
**Current Status**

At the moment the default behavior of motherlode is to cancel the whole import process if one dataloader fails (return code != 0)

**Desired Status**

It would be better to only cancel dependending following dataloders( dependencies are defined in defined in https://github.com/covidgraph/motherlode/blob/master/motherlode/data_sources_registry.py)

All independent dataloader tracks should just go on. 

**Profit**

Unattended failing import processes would advance in progress and the rerun after fixing the failed dataloader would take less time.

**Comment by frankschmitt** [comment]
I'll take a stab at this. Stay tuned :-)

**Comment by frankschmitt** [comment]
@motey I've created a PR for this. Would you like to review it, or should I merge it myself?

**Comment by motey** [comment]
Pretty cool :)  i will give it a test later or tomorrow

**Comment by motey** [comment]
just tested and looks good to me :)
Thanks Frank!
